# Generated by Django 2.1.7 on 2019-03-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190326_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to='static/services-img', verbose_name='rəsm'),
        ),
    ]
